### ISSUE TITLE
1.9V LDO型号

### ISSUE THREAD

**Issue by yoxiii** [Li-Dongze/stm32_paw3395_mouse#1]
![image](https://github.com/user-attachments/assets/06b784c4-1852-49eb-9951-98867fdc3031)
原原理图LDO型号为CE6219P33M,输出电压为3.3v，
是否应改为CE6219P18M?

**Comment by Li-Dongze** [comment]
![image](https://github.com/user-attachments/assets/ab790e9c-9587-40a9-9740-a9bd21597ff1)
感谢指出问题，仔细查阅数据手册发现确实是的，而且最好加两个1uf的电容，下版改正，感谢！
